#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# Generates JWT_SECRET + signed ANON_KEY + SERVICE_ROLE_KEY.
# Output is appended-ready: redirect into .env.
#
# Usage:
#   ./scripts/generate-keys.sh              # print to stdout
#   ./scripts/generate-keys.sh >> .env      # append to .env
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

if ! command -v node >/dev/null 2>&1; then
  echo "node is required" >&2
  exit 1
fi

JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(48).toString('base64url'))")

sign_jwt() {
  local role="$1"
  node -e "
    const crypto = require('crypto');
    const secret = process.argv[1];
    const role = process.argv[2];
    const b64 = b => Buffer.from(b).toString('base64')
      .replace(/=+\$/, '').replace(/\+/g, '-').replace(/\//g, '_');
    const header = b64(JSON.stringify({alg:'HS256', typ:'JWT'}));
    // 10 years validity
    const exp = Math.floor(Date.now()/1000) + 60*60*24*365*10;
    const payload = b64(JSON.stringify({
      role, iss:'supabase', iat: Math.floor(Date.now()/1000), exp
    }));
    const sig = b64(crypto.createHmac('sha256', secret).update(header+'.'+payload).digest());
    console.log(header+'.'+payload+'.'+sig);
  " "$JWT_SECRET" "$role"
}

ANON_KEY=$(sign_jwt anon)
SERVICE_KEY=$(sign_jwt service_role)

cat <<EOF

# ── Generated by scripts/generate-keys.sh on $(date -u +%FT%TZ) ──
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_KEY}
# VITE_SUPABASE_PUBLISHABLE_KEY must match ANON_KEY for the SPA:
VITE_SUPABASE_PUBLISHABLE_KEY=${ANON_KEY}
EOF
